config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resource :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  include AASM

  aasm whiny_transitions: false, column: 'state' do
    state :started, :initial => true
    state :scheduled, :completed, :cancelled

    event :schedule do
      transitions :from => :started, :to => :scheduled
    end

    event :complete do
      transitions :from => [:started, :scheduled], :to => :completed
    end

    event :cancel do
      transitions :from => [:started, :scheduled], :to => :cancelled
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout false, only: [:new]

  def index
    respond_to do |format|
      format.html do
        @tasks = Task.all
        render :index
      end
    end
  end

  def new
  end

  def create
  end

  def update
  end
  
  def destroy
    Task.find_by(id: params[:id]).destroy
    redirect_to root_path
  end

  def show
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    title = 'To Do List'
    = favicon_link_tag ''
    = stylesheet_link_tag :application, media: 'all'
    = javascript_include_tag :application
    = csrf_meta_tags

  body
    - unless current_user.nil?
      #menuHeader 
        nav.navbar.navbar-expand-lg.navbar-light.bg-primary
          #navbarText.collapse.navbar-collapse
            ul.navbar-nav.mr-auto
              li.nav-item
                a.nav-link.menuItems href="#" Taskboard
              li.nav-item.dropdown
                a.nav-link.dropdown-toggle.menuItems href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" Tasks
                .dropdown-menu
                  = link_to(:New, new_tasks_path, class: 'dropdown-item')
                  a.dropdown-item href="#" Completed 
                  a.dropdown-item href="#" Scheduled
              li.nav-item.dropdown
                a.nav-link.dropdown-toggle.menuItems href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" Users
                .dropdown-menu
                  a.dropdown-item href="#" New 
                  a.dropdown-item href="#" List 
              li.nav-item
                a.nav-link.menuItems href="#" Profile 
              li.nav-item
                = link_to(:LogOut, destroy_user_session_path, method: :delete, data: {confirm: 'Sign Out?', 'confirm-button-text': "Yes"}, class: 'nav-link menuItems')

    = yield

app/views/tasks/index.html.slim
br
- @tasks.in_batches(of: 4) do |task_batch|
  .row
    - task_batch.each do |task|
      .col-sm-3
        .card
          .card-body
            h5.card-title
              = task.name
            p.card-text
              = task.description
            a.btn.btn-primary.float-left href="#" Update
            = link_to(:Delete, tasks_path(id: task.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger float-right')
  br

app/views/tasks/new.html.slim
.modal tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5.modal-title Modal title
      .modal-body
        p Modal body text goes here
      .modal-footer
        button.btn.btn-primary type="button" Save changes
        button.btn.btn-secondary type="button" data-dismiss="modal" Close

h5.modal-title Modal title
p Modal body text goes here
button.btn.btn-primary type="button" Save changes